# Generated by Django 3.0.6 on 2020-05-26 03:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('32b69643-572e-4b42-a8e9-3348292992a5'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125, null=True)),
                ('mobile_number', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
