# Generated by Django 3.0.6 on 2020-05-27 05:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2e9cdc2c-029f-4310-b76e-d62e3363dc82'), primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='TestForeignkey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicapp.SignUp')),
            ],
        ),
    ]
