# Generated by Django 3.0.6 on 2020-05-27 06:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_auto_20200527_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='id',
            field=models.UUIDField(default=uuid.UUID('68bf60ce-caf5-4c12-a089-1ca1c0f80670'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='testforeignkey',
            name='id',
            field=models.UUIDField(default=uuid.UUID('84288065-ade7-4557-8ad1-1b2ddc94788c'), primary_key=True, serialize=False),
        ),
    ]
