# Generated by Django 3.0.6 on 2020-05-27 06:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0003_auto_20200527_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1612a96f-ebea-4ab9-9b2e-1d5cc7523aed'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='testforeignkey',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5fe1914d-731e-428f-818c-fc2f2f8e84f6'), primary_key=True, serialize=False),
        ),
    ]
