# Generated by Django 3.0.6 on 2020-05-29 19:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0004_auto_20200527_0644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testforeignkey',
            old_name='signup_id',
            new_name='signup',
        ),
        migrations.AlterField(
            model_name='signup',
            name='id',
            field=models.UUIDField(default=uuid.UUID('138c18ab-fb23-4e0e-af22-0b0f140702fa'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='testforeignkey',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c9506632-e392-44ed-8a8b-2c9a394a02d3'), primary_key=True, serialize=False),
        ),
    ]
